services:
  app:
    build: .
    container_name: php_app
    volumes:
      - ./:/var/www/html
    ports:
      - 8080:8000
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: my_database
      DB_USERNAME: user
      DB_PASSWORD: secret
    command: ["php", "-S", "0.0.0.0:8000", "-t", "/var/www/html"]
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootsecret
      MYSQL_DATABASE: my_database
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
    volumes:
      - db_data:/var/lib/mysql
      - ./init-dbs.sql:/docker-entrypoint-initdb.d/init-dbs.sql
    ports:
      - "3306:3306"
volumes:
  db_data:
