services:
  app:
    build: .
    container_name: php_app
    volumes:
      - ./:/var/www/html
    ports:
      - ${APP_PORT}:8000
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DB_HOST: db  # Override DB_HOST for Docker networking
    command: ["php", "-S", "0.0.0.0:8000", "-t", "/var/www/html/public"]
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./init-dbs.sql:/docker-entrypoint-initdb.d/init-dbs.sql
    ports:
      - ${DB_PORT}:3306
volumes:
  db_data:
