services:
  app:
    build: .
    container_name: php_app
    volumes:
      - ./:/var/www/html
    ports:
      - ${APP_PORT:-8000}:8000
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    command: ["php", "-S", "0.0.0.0:8000", "-t", "/var/www/html/public"]
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-nelsonrrj}
      MYSQL_DATABASE: ${DB_DATABASE:-my_database}
      MYSQL_USER: ${DB_USERNAME:-nelsonrrj}
      MYSQL_PASSWORD: ${DB_PASSWORD:-nelsonrrj}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - ${DB_PORT:-3306}:3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
volumes:
  db_data:
